name: 'Tag GitHub Action'

on: [workflow_dispatch]

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'

    - name: Execute GitVersion
      id: gitVersion
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
        useConfigFile: true

    - name: Tag Action
      shell: pwsh
      run: |
        Write-Host "GitVersion: $env:GitVersion_SemVer"

        $gitTags = git tag *>&1

        if ($gitTags -contains "v$( $env:GitVersion_SemVer )") {
          Write-Host "Tag v$( $env:GitVersion_SemVer ) found!"
        } else {
          if ($gitTags -contains "v$( $env:GitVersion_Major )") {
            Write-Host "Removing Tag: v$( $env:GitVersion_Major )"

            git push origin ":refs/tags/v$( $env:GitVersion_Major )"
          }

          git tag -a -m 'Version v$( $env:GitVersion_SemVer )' "vv$( $env:GitVersion_SemVer )"
          git tag -a -m 'Version v$( $env:GitVersion_Major )' "vv$( $env:GitVersion_Major )"
        }